# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_send',
                'doc_host': 'https://spence501.github.io',
                'git_url': 'https://github.com/spence501/nbdev_send',
                'lib_path': 'nbdev_send'},
  'syms': {'nbdev_send.core': {'nbdev_send.core.foo': ('core.html#foo', 'nbdev_send/core.py')}}}
